FROM node:20.11.0-alpine
RUN mkdir -p /app
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

ENV DB_HOST=$DB_HOST \
    DB_PORT=$DB_PORT \
    DB_USERNAME=$DB_USERNAME \
    DB_PASSWORD=$DB_PASSWORD \
    DB_NAME=$DB_NAME \
    DB_SYNC=$DB_SYNC \
    JWT_SECRET_KEY=$JWT_SECRET_KEY \
    ES_ENDPOINT=$ES_ENDPOINT \
    ES_USERNAME=$ES_USERNAME \
    ES_PASSWORD=$ES_PASSWORD \
    KAKAO_REST_API_KEY=$KAKAO_REST_API_KEY \
    KAKAO_REDIRECT_URI=$KAKAO_REDIRECT_URI \
    AWS_REGION=$AWS_REGION \
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    S3_BUCKET_NAME=$S3_BUCKET_NAME \
    AWS_SECRET_KEY=$AWS_SECRET_KEY

EXPOSE 3000
CMD ["npm", "run", "start:prod"]