# compose 파일 버전
version: "3"
services: 
  # 서비스 명
  backend:
    # 사용할 이미지
    image: raffle
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: raffle.service
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "3000:3000"
    # 볼륨 설정
    volumes:
      - ./data/raffle/:/var/lib
    networks:
      - raffle-networks

networks:
  raffle-networks: