name: Nestjs CI

on:
  push:
    branches: [feat/markets]
  pull_request:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      # - name: Run lint
      #   run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      # - name: Run lint
      #   run: npm run lint
      - name: Run tests
        run: npm test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # 나의 ECR 정보
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ secrets.ECR_REGISTRY }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}

        run: |
          docker build --build-arg DB_HOST=${{ env.DB_HOST }} \
          --build-arg DB_PORT=${{ env.DB_PORT }} \
          --build-arg DB_USERNAME=${{ env.DB_USERNAME }} \
          --build-arg DB_PASSWORD=${{ env.DB_PASSWORD }} \
          --build-arg DB_NAME=${{ env.DB_NAME }} \
          --build-arg DB_SYNC=${{ env.DB_SYNC }} \
          --build-arg JWT_SECRET_KEY=${{ env.JWT_SECRET_KEY }} \
          --build-arg ES_ENDPOINT=${{ env.ES_ENDPOINT }} \
          --build-arg ES_USERNAME=${{ env.ES_USERNAME }} \
          --build-arg ES_PASSWORD=${{ env.ES_PASSWORD }} \
          --build-arg KAKAO_REST_API_KEY=${{ env.KAKAO_REST_API_KEY }} \
          --build-arg KAKAO_REDIRECT_URI=${{ env.KAKAO_REDIRECT_URI }} \
          --build-arg AWS_REGION=${{ env.AWS_REGION }} \
          --build-arg AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }} \
          --build-arg S3_BUCKET_NAME=${{ env.S3_BUCKET_NAME }} \
          --build-arg AWS_SECRET_KEY=${{ env.AWS_SECRET_KEY }} \
            -t $REPOSITORY .
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_HH-mm-ss
          utcOffset: '+09:00'

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp Dockerrun.aws.json deploy/Dockerrun.aws.json
          cd deploy && zip -r deploy.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: raffles-eb-app
          environment_name: Raffles-eb-app-env
          version_label: earth-docker-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 200
